version: 2.1

defaults: &defaults
  resource_class: medium
  steps:
  - startup
  - build
  environment:
    OPAMJOBS: 2
    OPAMVERBOSE: 1
    OPAMWITHTEST: true
    OPAMYES: true
    TERM: xterm

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
  build:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          opam update
          opam install --deps-only ./
    - run:
        name: List installed packages
        command: opam list
    - run:
        name: Build and test
        command: opam install .
    - run:
        name: Uninstall
        command: opam remove .

jobs:
  coq 8_10:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.10
  coq 8_11:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.11
  coq dev:
    <<: *defaults
    docker:
    - image: coqorg/coq:dev

workflows:
  version: 2
  build:
    jobs:
    - coq 8_10
    - coq 8_11
    - coq dev
